import json

from normalization.proof import canonicalize_module_name, canonicalize_proof_text
from scripts import proof_canonical_diff as diff_cli
from scripts import proof_hash_backfill as backfill


def _sample_proof(job_id: str) -> str:
    return (
        "import Mathlib\n\n"
        "namespace ML.Jobs\n\n"
        f"/-- Auto-generated by MathLedger worker for job {job_id} -/\n"
        f"theorem job_{job_id} (p : Prop) : p := by\n"
        "  intro hp  \n"
        "  exact hp\n"
        "\n"
        "end ML.Jobs\n"
    )


def test_summarize_row_flags_hash_change() -> None:
    row = {
        "id": 42,
        "statement_hash": "a" * 64,
        "prover": "lean4",
        "status": "success",
        "proof_text": _sample_proof("deadbeefcaf0"),
        "module_name": "ML.Jobs.job_deadbeefcaf0",
        "derivation_rule": "axiom",
        "proof_hash": "legacy",
    }
    summary = backfill.summarize_row(row)
    assert summary["proof_id"] == 42
    assert summary["changed"] is True
    assert summary["old_hash"] == "legacy"
    assert summary["new_hash"]
    assert isinstance(summary["new_hash"], str)
    assert len(summary["new_hash"]) == 64


def test_build_diff_includes_job_scrub() -> None:
    original = _sample_proof("deadbeef0000")
    canonical = canonicalize_proof_text(original)
    module_name = "ML.Jobs.job_deadbeef0000"
    canonical_module = canonicalize_module_name(module_name)
    diff_text = diff_cli.build_diff(original, canonical, module_name, canonical_module)
    assert "-theorem job_deadbeef0000" in diff_text
    assert "+theorem job_CANONICAL" in diff_text
    assert "-ML.Jobs.job_deadbeef0000" in diff_text
    assert "+ML.Jobs.job_CANONICAL" in diff_text


def test_emit_report_writes_jsonl(tmp_path) -> None:
    rows = [
        {
            "id": 1,
            "statement_hash": "a" * 64,
            "prover": "lean4",
            "status": "success",
            "proof_text": _sample_proof("111111"),
            "module_name": "ML.Jobs.job_111111",
            "derivation_rule": "axiom",
            "proof_hash": "legacy",
        },
        {
            "id": 2,
            "statement_hash": "b" * 64,
            "prover": "lean4",
            "status": "success",
            "proof_text": _sample_proof("222222"),
            "module_name": "ML.Jobs.job_222222",
            "derivation_rule": "axiom",
            "proof_hash": "legacy",
        },
    ]
    out_path = tmp_path / "report.jsonl"
    builder = backfill.GovernanceReportBuilder()
    with out_path.open("w", encoding="utf-8") as fh:
        backfill.emit_report(iter(rows), fh, builder)
    lines = out_path.read_text(encoding="utf-8").strip().splitlines()
    assert len(lines) == 2
    parsed = [json.loads(line) for line in lines]
    assert parsed[0]["proof_id"] == 1
    assert parsed[1]["proof_id"] == 2


def test_governance_report_builder_counts() -> None:
    builder = backfill.GovernanceReportBuilder(sample_limit=1)
    builder.update({"proof_id": 1, "old_hash": "aaa", "new_hash": "aaa", "changed": False})
    builder.update({"proof_id": 2, "old_hash": "bbb", "new_hash": "ccc", "changed": True})
    report = builder.build()
    assert report["schema_version"] == "1.0.0"
    assert report["total_proofs"] == 2
    assert report["changed_count"] == 1
    assert report["unchanged_count"] == 1
    assert report["sample_changed"] == [{"proof_id": 2, "old_hash": "bbb", "new_hash": "ccc"}]
