name: Verification V2 - Audit Sync

on:
  pull_request:
    branches: [ integrate/ledger-v0.1 ]
  push:
    branches: [ integrate/ledger-v0.1 ]
  workflow_dispatch:

jobs:
  verify-audit-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: astral-sh/setup-uv@v1
      
      - name: Install dependencies
        run: uv sync
      
      - name: Run Universal Verifier V2 (Offline)
        id: verify
        run: |
          mkdir -p artifacts/audit
          uv run python tools/verify_all_v2.py \
            --offline \
            --verbose \
            --audit-sync \
            --output artifacts/audit/verification_summary.json
        continue-on-error: true
      
      - name: Display Verification Summary
        if: always()
        run: |
          if [ -f artifacts/audit/verification_summary.md ]; then
            echo "## Verification V2 Summary" >> $GITHUB_STEP_SUMMARY
            cat artifacts/audit/verification_summary.md >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: Upload Audit Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: verification-audit-${{ github.run_number }}
          path: |
            artifacts/audit/verification_summary.json
            artifacts/audit/verification_summary.md
            artifacts/audit/exit_code_map.json
          retention-days: 30
      
      - name: Validate Exit Code
        if: always()
        run: |
          if [ -f artifacts/audit/verification_summary.json ]; then
            EXIT_CODE=$(jq -r '.exit_code' artifacts/audit/verification_summary.json)
            ALLBLUE_STATUS=$(jq -r '.exit_code_map.allblue_status' artifacts/audit/verification_summary.json)
            
            echo "Exit Code: $EXIT_CODE"
            echo "AllBlue Status: $ALLBLUE_STATUS"
            
            if [ "$EXIT_CODE" -eq 0 ]; then
              echo "✅ [PASS] VERIFIED: ALL CLAIMS HOLD (sync v2)"
              exit 0
            else
              echo "❌ [FAIL] Verification failed"
              exit 1
            fi
          else
            echo "⚠️ [ERROR] Verification summary not found"
            exit 2
          fi
      
      - name: Auto-commit audit results on main push
        if: github.ref == 'refs/heads/integrate/ledger-v0.1' && github.event_name == 'push'
        run: |
          git config --local user.email "devin-ai-integration[bot]@users.noreply.github.com"
          git config --local user.name "Devin AI"
          
          if [ -d "artifacts/audit" ]; then
            git add artifacts/audit/
            if ! git diff --cached --quiet; then
              git commit -m "ci: update verification audit results [skip ci]
              
              Auto-generated verification V2 audit results.
              - verification_summary.json: Signed verification results
              - verification_summary.md: CI-friendly summary
              - exit_code_map.json: AllBlue ingestion mapping"
              git push origin integrate/ledger-v0.1
            fi
          fi
