from ledger.ingest import _canonical_json
from normalization.proof import (
    canonicalize_module_name,
    canonicalize_proof_bytes,
    canonicalize_proof_text,
)
from substrate.crypto.hashing import DOMAIN_ROOT, sha256_hex


def _sample_proof(job_id: str) -> str:
    return f"""import Mathlib\r
\r
namespace ML.Jobs\r
\r
/-- Auto-generated by MathLedger worker for job {job_id} -/\r
set_option linter.unusedVariables false\r
theorem job_{job_id} (p q : Prop) : p -> p := by\r
  intro hp  \r
  exact hp\r
\r
end ML.Jobs\r
"""


def _proof_hash(proof_text: str, module_name: str) -> str:
    canonical_proof = canonicalize_proof_text(proof_text)
    canonical_module = canonicalize_module_name(module_name)
    payload = {
        "statement_hash": "abc123",
        "prover": "lean4",
        "status": "success",
        "proof_text": canonical_proof,
        "module": canonical_module,
        "derivation_rule": "axiom",
    }
    payload_json = _canonical_json(payload)
    return sha256_hex(payload_json, domain=DOMAIN_ROOT)


def test_canonicalize_proof_text_scrubs_job_id() -> None:
    proof = _sample_proof("abc123def456")
    canonical = canonicalize_proof_text(proof)
    assert "abc123def456" not in canonical
    assert "job CANONICAL" in canonical  # comment scrub
    assert "job_CANONICAL" in canonical  # theorem name scrub
    assert "\r" not in canonical
    assert canonical.endswith("\n")


def test_canonicalize_proof_bytes_ascii() -> None:
    proof = "theorem job_deadbeef1234 : True := by\n  trivial\n"
    payload = canonicalize_proof_bytes(proof)
    payload.decode("ascii")  # Should not raise


def test_proof_hash_stable_across_job_ids() -> None:
    proof_a = _sample_proof("abc123def456")
    proof_b = _sample_proof("def456abc123")
    module_a = "ML.Jobs.job_abc123def456"
    module_b = "ML.Jobs.job_def456abc123"
    assert _proof_hash(proof_a, module_a) == _proof_hash(proof_b, module_b)
