"""
MathLedger Metrics Package.

Provides telemetry emission and collection for various subsystems.
"""

from backend.metrics.first_organism_telemetry import (
    FirstOrganismRunResult,
    FirstOrganismTelemetry,
    emit_first_organism_metrics,
    get_telemetry,
)
from backend.metrics.statistical import (
    compute_wilson_ci,
    detect_temporal_success_drift,
    detect_policy_weight_drift,
    detect_metric_instability,
    DriftResult,
    rolling_average,
    rolling_variance,
    stability_index,
    abstention_trend,
    validate_series,
)
from backend.metrics.drift_alignment import (
    MetricDriftSignature,
    DriftAlignmentResult,
    StabilityEnvelope,
    CIGateResult,
    DriftCell,
    compute_drift_alignment,
    generate_stability_envelope,
    generate_multi_metric_envelopes,
    compute_monotonicity,
    compute_pearson_correlation,
    analyze_drift_monotonicity,
    evaluate_drift_for_ci,
    classify_pattern_hint,
    get_drift_thresholds,
    validate_drift_thresholds,
    build_drift_cells,
    drift_cells_to_dicts,
    summarize_slice_drift,
    evaluate_drift_for_promotion,
    summarize_drift_for_global_health,
    build_drift_trend_history,
    evaluate_drift_trend_for_promotion,
    build_drift_director_panel,
    CORE_UPLIFT_METRICS,
    build_multi_axis_drift_view,
    summarize_drift_for_uplift_envelope,
    DRIFT_AXES,
    build_drift_tensor,
    build_drift_poly_cause_analyzer,
    build_drift_director_tile_v2,
    DRIFT_TENSOR_SCHEMA_VERSION,
    snapshot_thresholds,
    verify_thresholds_unchanged,
    PATTERN_HINTS,
    DRIFT_THRESHOLDS,
    VALID_PROFILES,
    DRIFT_CELL_COLUMNS,
)
from backend.metrics.metric_conformance_snapshot import (
    ConformanceLevel,
    DriftClass,
    MetricConformanceResult,
    ConformanceSnapshot,
    SnapshotComparison,
    DriftEvent,
    DriftLedger,
    PromotionReadiness,
    GlobalHealthStatus,
    build_conformance_snapshot,
    save_conformance_snapshot,
    load_conformance_snapshot,
    compare_conformance_snapshots,
    can_promote_metric,
    build_metric_drift_ledger,
    compute_metric_promotion_readiness,
    summarize_metric_conformance_for_global_health,
    # Phase IV: Conformance Drift Compass & Promotion Dashboard
    build_metric_drift_compass,
    summarize_conformance_for_promotion_dashboard,
    build_conformance_director_panel,
    # Phase V: Metrics × Budget × Policy Triangulation
    build_metric_budget_joint_view,
    summarize_conformance_for_global_console,
    attach_policy_telemetry_hint,
    # Phase VI: Metrics + Budget as One Governance Surface
    summarize_conformance_and_budget_for_global_console,
    to_governance_signal_for_metrics,
    render_conformance_report,
    get_git_sha,
    DRIFT_TO_CONFORMANCE,
)

__all__ = [
    # First Organism telemetry
    "FirstOrganismRunResult",
    "FirstOrganismTelemetry",
    "emit_first_organism_metrics",
    "get_telemetry",
    # Statistical metrics (Phase II)
    "compute_wilson_ci",
    "detect_temporal_success_drift",
    "detect_policy_weight_drift",
    "detect_metric_instability",
    "DriftResult",
    "rolling_average",
    "rolling_variance",
    "stability_index",
    "abstention_trend",
    "validate_series",
    # Drift Alignment Engine (Phase II)
    "MetricDriftSignature",
    "DriftAlignmentResult",
    "StabilityEnvelope",
    "CIGateResult",
    "compute_drift_alignment",
    "generate_stability_envelope",
    "generate_multi_metric_envelopes",
    "compute_monotonicity",
    "compute_pearson_correlation",
    "analyze_drift_monotonicity",
    # CI/Tooling helpers
    "evaluate_drift_for_ci",
    "classify_pattern_hint",
    "get_drift_thresholds",
    "validate_drift_thresholds",
    # Drift cells grid
    "DriftCell",
    "build_drift_cells",
    "drift_cells_to_dicts",
    "DRIFT_CELL_COLUMNS",
    # Phase III: Promotion Radar & Global Drift Signal
    "summarize_slice_drift",
    "evaluate_drift_for_promotion",
    "summarize_drift_for_global_health",
    # Phase IV: Drift-Aware Promotion & Global Drift Intelligence
    "build_drift_trend_history",
    "evaluate_drift_trend_for_promotion",
    "build_drift_director_panel",
    "CORE_UPLIFT_METRICS",
    # Phase V: Cross-Metric Drift Coupler & Multi-Axis Drift Summary
    "build_multi_axis_drift_view",
    "summarize_drift_for_uplift_envelope",
    "DRIFT_AXES",
    # Phase VI: Drift Tensor & Poly-Cause Analysis
    "build_drift_tensor",
    "build_drift_poly_cause_analyzer",
    "build_drift_director_tile_v2",
    "DRIFT_TENSOR_SCHEMA_VERSION",
    # Threshold snapshot
    "snapshot_thresholds",
    "verify_thresholds_unchanged",
    # Constants
    "PATTERN_HINTS",
    "DRIFT_THRESHOLDS",
    "VALID_PROFILES",
    # Metric Conformance Snapshot (Phase II)
    "ConformanceLevel",
    "DriftClass",
    "MetricConformanceResult",
    "ConformanceSnapshot",
    "SnapshotComparison",
    "build_conformance_snapshot",
    "save_conformance_snapshot",
    "load_conformance_snapshot",
    "compare_conformance_snapshots",
    "can_promote_metric",
    "render_conformance_report",
    "get_git_sha",
    "DRIFT_TO_CONFORMANCE",
    # Phase III: Drift Memory & Promotion Oracle
    "DriftEvent",
    "DriftLedger",
    "PromotionReadiness",
    "GlobalHealthStatus",
    "build_metric_drift_ledger",
    "compute_metric_promotion_readiness",
    "summarize_metric_conformance_for_global_health",
    # Phase IV: Conformance Drift Compass & Promotion Dashboard
    "build_metric_drift_compass",
    "summarize_conformance_for_promotion_dashboard",
    "build_conformance_director_panel",
    # Phase V: Metrics × Budget × Policy Triangulation
    "build_metric_budget_joint_view",
    "summarize_conformance_for_global_console",
    "attach_policy_telemetry_hint",
    # Phase VI: Metrics + Budget as One Governance Surface
    "summarize_conformance_and_budget_for_global_console",
    "to_governance_signal_for_metrics",
]
