name: Hermetic Matrix Health

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  workflow_dispatch:  # Manual trigger for testing

permissions:
  contents: write  # For committing history updates
  actions: read    # For reading workflow run status

jobs:
  track-matrix:
    runs-on: ubuntu-latest
    if: always()  # Run even if CI failed
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Validate Current Hermetic State
        id: validate
        run: |
          python tools/hermetic/matrix_trend.py --validate
        continue-on-error: true
      
      - name: Append Matrix History
        id: append
        run: |
          python tools/hermetic/matrix_trend.py --append
        continue-on-error: true
      
      - name: Validate History
        id: validate-history
        run: |
          python tools/hermetic/matrix_trend.py --validate-history --required-runs 3
        continue-on-error: true
      
      - name: Check for Drift
        id: drift
        run: |
          if ! python tools/hermetic/matrix_trend.py --alert-drift-abstain --threshold 3; then
            echo "drift=true" >> $GITHUB_OUTPUT
            echo "::warning::H_matrix drift detected - see drift_report.txt"
          else
            echo "drift=false" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true
      
      - name: Verify Global Matrix
        id: verify-global
        run: |
          if python tools/hermetic/matrix_trend.py --verify-global --num-shards 16; then
            echo "global_verified=true" >> $GITHUB_OUTPUT
          else
            echo "global_verified=false" >> $GITHUB_OUTPUT
            echo "::warning::Global H-Matrix verification failed - missing shard data"
          fi
        continue-on-error: true
      
      - name: Generate Global Matrix Summary
        if: always()
        run: |
          python tools/hermetic/matrix_trend.py --save-global --num-shards 16
      
      - name: Reshard if Large
        if: always()
        run: |
          H=$(wc -l < artifacts/no_network/matrix_history.jsonl || echo 0)
          if [ "$H" -gt 100 ]; then
            python tools/hermetic/reshard_history.py --num-shards 64
          else
            echo "History size: $H entries (threshold: 100)"
            echo "Skipping resharding"
          fi
      
      - name: Append Global Root
        if: always()
        run: |
          python tools/hermetic/matrix_trend.py --append-global-root --num-shards 64
        continue-on-error: true
      
      - name: Alert Global Drift
        id: global-drift
        if: always()
        run: |
          python tools/hermetic/matrix_trend.py --alert-global-drift --num-shards 64 --threshold 3 || true
        continue-on-error: true
      
      - name: Generate Matrix Report
        if: always()
        run: |
          python tools/hermetic/matrix_trend.py --save-report --limit 10
          
          echo "## ðŸ”’ Hermetic Matrix Health Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat artifacts/no_network/matrix_report.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          
          if [ -f artifacts/no_network/drift_report.txt ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "## âš ï¸ Drift Report" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat artifacts/no_network/drift_report.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -f artifacts/hermetic/global_matrix.json ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "## ðŸŒ Global Matrix Summary" >> $GITHUB_STEP_SUMMARY
            echo '```json' >> $GITHUB_STEP_SUMMARY
            cat artifacts/hermetic/global_matrix.json >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -f artifacts/hermetic/global_drift_report.txt ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "## ðŸ”„ Global Drift Report" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat artifacts/hermetic/global_drift_report.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: Upload Matrix Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hermetic-matrix-health-${{ github.run_number }}
          path: |
            artifacts/no_network/matrix_history.jsonl
            artifacts/no_network/matrix_report.txt
            artifacts/no_network/drift_report.txt
            artifacts/hermetic/global_matrix.json
            artifacts/hermetic/global_root_history.jsonl
            artifacts/hermetic/global_drift_report.txt
            artifacts/hermetic/shard_*.jsonl
            artifacts/hermetic/shard_manifest.json
          retention-days: 90
      
      - name: Commit Updated History
        if: |
          always() &&
          (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/integrate/ledger-v0.1') &&
          steps.append.outcome == 'success'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add artifacts/no_network/matrix_history.jsonl
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci: update hermetic matrix history [skip ci]"
            git push
          fi
