name: Composite Dual Attestation Gate

on:
  push:
    branches: [ integrate/ledger-v0.1, main ]
  pull_request:
    branches: [ integrate/ledger-v0.1, main ]

jobs:
  composite-da:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Verify artifacts exist
      run: |
        echo "Checking for required artifact files..."
        if [ ! -f "artifacts/ui/roots.json" ]; then
          echo "WARNING: UI roots.json not found"
        fi
        if [ ! -f "artifacts/reasoning/roots.json" ]; then
          echo "WARNING: Reasoning roots.json not found"
        fi

    - name: Run Composite DA Workflow
      id: composite_da
      run: |
        python3 tools/composite_da.py > da_output.txt 2>&1
        exit_code=$?
        cat da_output.txt

        # Extract summary lines
        echo "=== CI Summary ==="
        grep "UI_MERKLE_ROOT:" da_output.txt || echo "UI_MERKLE_ROOT: MISSING"
        grep "REASONING_MERKLE_ROOT:" da_output.txt || echo "REASONING_MERKLE_ROOT: MISSING"
        grep "COMPOSITE_DA_TOKEN:" da_output.txt || echo "COMPOSITE_DA_TOKEN: ABSTAIN"

        exit $exit_code

    - name: Verify ASCII compliance
      run: |
        echo "Verifying ASCII-only output..."
        if file da_output.txt | grep -q "ASCII text"; then
          echo " ASCII compliance verified"
        else
          echo " Non-ASCII content detected"
          exit 1
        fi

    - name: Upload DA artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: composite-da-output
        path: |
          da_output.txt
          artifacts/ui/roots.json
          artifacts/reasoning/roots.json

