# .github/workflows/gate-powershell-drift.yml
name: 'Gate: PowerShell Drift'

on:
  pull_request:
    paths:
      - 'backend/**/*.py'
      - 'scripts/testing/ps_drift_server.py'
      - 'scripts/testing/run_ps_drift_tests.ps1'
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  test-powershell-interop:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip3 install flask

      - name: Start Test Server (Unix)
        if: runner.os != 'Windows'
        run: |
          python3 scripts/testing/ps_drift_server.py &
          sleep 3

      - name: Start Test Server (Windows)
        if: runner.os == 'Windows'
        run: |
          Start-Process python -ArgumentList "scripts/testing/ps_drift_server.py" -WindowStyle Hidden
          Start-Sleep -Seconds 3

      - name: Run PowerShell Drift Tests
        shell: pwsh
        run: |
          ./scripts/testing/run_ps_drift_tests.ps1

      - name: Upload Drift Report
        if: always()
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: powershell-drift-report-${{ matrix.os }}
          path: ps_drift_report.json
          retention-days: 7

      - name: Comment PR with Drift Summary (Ubuntu only)
        if: always() && github.event_name == 'pull_request' && matrix.os == 'ubuntu-latest'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const fs = require('fs');
            const reportPath = 'ps_drift_report.json';
            
            if (fs.existsSync(reportPath)) {
              const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
              const emoji = report.failed === 0 && report.errors === 0 ? '✅' : '❌';
              const status = report.failed === 0 && report.errors === 0 ? 'PASS' : 'FAIL';
              
              const body = `## ${emoji} PowerShell Drift Report: ${status}

**Test Summary:**
- Total: ${report.total_tests}
- Passed: ${report.passed}
- Failed: ${report.failed}
- Errors: ${report.errors}

Cross-platform testing matrix: Linux, macOS, Windows
              `;
              
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              });
            }
