# .github/workflows/gate-telemetry-drift.yml
name: 'Gate: Telemetry Drift'

on:
  pull_request:
    paths:
      - 'backend/telemetry/**'
      - 'scripts/generators/generate_telemetry_snapshot.py'
      - 'scripts/radars/telemetry_drift_radar.py'

jobs:
  detect-drift:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip3 install canonicaljson

      - name: Generate Current Snapshot
        run: |
          mkdir -p artifacts/drift
          python3 scripts/generators/generate_telemetry_snapshot.py > artifacts/drift/current_snapshot.json

      - name: Get Baseline Snapshot
        run: |
          git show origin/${{ github.base_ref || 'main' }}:artifacts/governance/telemetry_schema_snapshot.json > artifacts/drift/baseline_snapshot.json 2>/dev/null || \
          echo '{"version":"1.0.0","timestamp":"1970-01-01T00:00:00Z","events":{}}' > artifacts/drift/baseline_snapshot.json

      - name: Run Telemetry Drift Radar
        run: |
          set -e
          python3 scripts/radars/telemetry_drift_radar.py \
            --baseline artifacts/drift/baseline_snapshot.json \
            --current artifacts/drift/current_snapshot.json \
            --output-dir artifacts/drift

      - name: Upload Drift Report
        if: always()
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: telemetry-drift-report
          path: artifacts/drift/
          retention-days: 7

      - name: Comment PR with Drift Summary
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const fs = require('fs');
            const summaryPath = 'artifacts/drift/telemetry_drift_summary.md';
            
            if (fs.existsSync(summaryPath)) {
              const summary = fs.readFileSync(summaryPath, 'utf8');
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## 📡 Telemetry Drift Report\n\n${summary}`
              });
            }
