name: Wonder Scan Determinism

on:
  pull_request:
    paths:
      - 'scripts/wonder_scan.py'
      - 'artifacts/wpv5/**'
      - 'artifacts/repro/**'
      - '.github/workflows/wonder-scan.yml'
  push:
    branches:
      - main
      - integrate/**
    paths:
      - 'scripts/wonder_scan.py'
      - 'artifacts/wpv5/**'
      - 'artifacts/repro/**'
  workflow_dispatch:

jobs:
  wonder-scan:
    runs-on: ubuntu-latest
    env:
      NO_NETWORK: "true"
      PYTHONPATH: "."
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Run Wonder Scan (stable timestamp) - Run 1
        run: |
          python3 scripts/wonder_scan.py --stable-ts --verbose
          cp artifacts/wonder/insights.json artifacts/wonder/insights.run1.json
          echo "Run 1 complete"
      
      - name: Run Wonder Scan (stable timestamp) - Run 2
        run: |
          python3 scripts/wonder_scan.py --stable-ts --verbose
          cp artifacts/wonder/insights.json artifacts/wonder/insights.run2.json
          echo "Run 2 complete"
      
      - name: Byte-identical check
        id: determinism_check
        run: |
          echo "Comparing Run 1 and Run 2 outputs..."
          if diff -q artifacts/wonder/insights.run1.json artifacts/wonder/insights.run2.json; then
            echo "status=PASS" >> $GITHUB_OUTPUT
            echo "[PASS] Wonder Scan Deterministic & ASCII" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Two consecutive runs with --stable-ts produced byte-identical outputs." >> $GITHUB_STEP_SUMMARY
          else
            echo "status=FAIL" >> $GITHUB_OUTPUT
            echo "[FAIL] Wonder Scan Determinism Check Failed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Outputs differ:" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            diff artifacts/wonder/insights.run1.json artifacts/wonder/insights.run2.json >> $GITHUB_STEP_SUMMARY || true
            echo '```' >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
      
      - name: ASCII compliance check
        run: |
          echo "Checking ASCII compliance..."
          python3 -c "
          import sys
          files = ['artifacts/wonder/insights.json', 'artifacts/wonder/README.md', 'artifacts/wonder/verification_report.md']
          for f in files:
              try:
                  with open(f, 'rb') as file:
                      content = file.read()
                      content.decode('ascii')
                      print(f'{f}: ASCII PASS')
              except FileNotFoundError:
                  print(f'{f}: SKIP (not found)')
              except UnicodeDecodeError as e:
                  print(f'{f}: ASCII FAIL - {e}')
                  sys.exit(1)
          print('All Wonder Scan artifacts: ASCII-compliant')
          "
      
      - name: Extract and display insights summary
        if: success()
        run: |
          echo "## Wonder Scan Insights Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          python3 << 'EOF' >> $GITHUB_STEP_SUMMARY
          import json
          
          with open('artifacts/wonder/insights.json') as f:
              insights = json.load(f)
          
          print(f"**Overall Health**: {insights['overall_health']}")
          print(f"**Signal Strength**: {insights['average_signal_strength']}")
          print(f"**Scan Status**: {insights['scan_status']}")
          print("")
          print("### Key Findings")
          print("")
          
          for name, data in insights['insights'].items():
              status = data.get('status', 'UNKNOWN')
              signal = data.get('signal_strength', 0.0)
              print(f"- **{name.replace('_', ' ').title()}**: {status} (signal: {signal})")
          
          if insights.get('recommendations'):
              print("")
              print("### Recommendations")
              print("")
              for i, rec in enumerate(insights['recommendations'], 1):
                  print(f"{i}. {rec}")
          EOF
      
      - name: Upload Wonder Scan artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: wonder-insights
          path: |
            artifacts/wonder/*.json
            artifacts/wonder/*.md
          retention-days: 30
      
      - name: Fail if determinism check failed
        if: steps.determinism_check.outputs.status == 'FAIL'
        run: |
          echo "Determinism check failed. See summary for details."
          exit 1

