name: Weekly Proof-of-Build

on:
  schedule:
    # Run every Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  issues: write

jobs:
  flightdeck:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found"
      
      - name: Run flight deck
        id: flightdeck
        run: |
          python tools/devin_e_toolbox/flightdeck.py --run
          
          # Extract signature from report
          SIGNATURE=$(python -c "import json; print(json.load(open('artifacts/ops/flightdeck.json'))['signature'])")
          echo "signature=$SIGNATURE" >> $GITHUB_OUTPUT
          
          # Extract timestamp
          TIMESTAMP=$(python -c "import json; print(json.load(open('artifacts/ops/flightdeck.json'))['timestamp'])")
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
          
          # Extract success count
          SUCCESS_COUNT=$(python -c "import json; d=json.load(open('artifacts/ops/flightdeck.json')); print(f\"{d['success_count']}/{d['total_count']}\")")
          echo "success_count=$SUCCESS_COUNT" >> $GITHUB_OUTPUT
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flightdeck-report
          path: |
            artifacts/ops/flightdeck.json
            artifacts/perf/perf_log.json
            artifacts/audit/audit_trail.jsonl
            artifacts/allblue/fleet_state.json
      
      - name: Create or update issue
        uses: actions/github-script@v7
        with:
          script: |
            const signature = '${{ steps.flightdeck.outputs.signature }}';
            const timestamp = '${{ steps.flightdeck.outputs.timestamp }}';
            const successCount = '${{ steps.flightdeck.outputs.success_count }}';
            const runUrl = `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
            
            // Find existing issue
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['weekly-proof-of-build'],
              state: 'open'
            });
            
            const body = `## Weekly Proof-of-Build Report
            
**Timestamp**: ${timestamp}  
**Signature**: \`${signature}\`  
**Success**: ${successCount}  
**Run**: [View workflow run](${runUrl})

### Artifacts

- [Flight Deck Report](${runUrl}#artifacts)
- [Performance Log](${runUrl}#artifacts)
- [Audit Trail](${runUrl}#artifacts)
- [Fleet State](${runUrl}#artifacts)

### Pass-Line

\`\`\`
[PASS] Flight Deck: ${signature}
\`\`\`

### Operations Executed

1. **velocity seal** - CI velocity measurement
2. **audit chain** - Audit trail sync+verify
3. **allblue freeze** - Fleet state archival

All operations produce RFC 8785 sealed artifacts with deterministic hashes.

---

*This issue is automatically updated weekly by the [Weekly Proof-of-Build workflow](${runUrl}).*
`;
            
            if (issues.data.length > 0) {
              // Update existing issue
              const issue = issues.data[0];
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: body
              });
              
              // Add comment with new run
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: `**New run completed**: ${timestamp}\n\`\`\`\n[PASS] Flight Deck: ${signature}\n\`\`\`\n[View artifacts](${runUrl}#artifacts)`
              });
              
              console.log(`Updated issue #${issue.number}`);
            } else {
              // Create new issue
              const newIssue = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Weekly Proof-of-Build',
                body: body,
                labels: ['weekly-proof-of-build', 'automation']
              });
              
              console.log(`Created issue #${newIssue.data.number}`);
            }
