#!/usr/bin/env python3
"""
Post AllBlue Epoch Seal PR comment with witness signatures.

Reads epoch seal data and posts a formatted comment to the PR.
"""

import json
import os
import subprocess
import sys
from typing import Dict, Any, Optional


def get_pr_number() -> Optional[int]:
    """Get PR number from GitHub Actions environment or git branch."""
    
    pr_number = os.environ.get('GITHUB_PR_NUMBER')
    if pr_number:
        return int(pr_number)
    
    event_path = os.environ.get('GITHUB_EVENT_PATH')
    if event_path and os.path.exists(event_path):
        with open(event_path, 'r') as f:
            event = json.load(f)
            if 'pull_request' in event:
                return event['pull_request']['number']
    
    try:
        result = subprocess.run(
            ['gh', 'pr', 'view', '--json', 'number'],
            capture_output=True,
            text=True,
            check=True
        )
        pr_data = json.loads(result.stdout)
        return pr_data.get('number')
    except Exception:
        return None


def load_fleet_state(fleet_state_path: str) -> Dict[str, Any]:
    """Load fleet state from JSON file."""
    with open(fleet_state_path, 'r') as f:
        return json.load(f)


def format_witness_status(witness_sig: str) -> str:
    """Format witness signature for display."""
    if witness_sig.startswith('ABSTAIN:'):
        return f"⚠️ ABSTAIN ({witness_sig.split(':', 1)[1]})"
    elif len(witness_sig) == 64:
        return f"✅ `{witness_sig[:16]}...`"
    else:
        return f"❌ Invalid"


def generate_pr_comment(fleet_state: Dict[str, Any]) -> str:
    """Generate PR comment with epoch seals and witness list."""
    
    status = fleet_state['allblue_status']
    epoch_hash = fleet_state['epoch_hash']
    witnessed_epoch_hash = fleet_state['witnessed_epoch_hash']
    witnesses = fleet_state['witnesses']
    
    status_emoji = {
        'PASS': '✅',
        'ABSTAIN': '⚠️',
        'FAIL': '❌'
    }.get(status, '❓')
    
    comment = f"""## {status_emoji} AllBlue Epoch Seal - {status}


**Base Epoch Seal:**
```
{epoch_hash}
```

**Witnessed Epoch Seal (Crown Seal):**
```
{witnessed_epoch_hash}
```


| Witness | Status | Signature |
|---------|--------|-----------|
| Verification Gate | {format_witness_status(witnesses.get('verification_gate_sig', 'ABSTAIN:missing'))} | `{witnesses.get('verification_gate_sig', 'N/A')[:32]}...` |
| Hermetic Matrix | {format_witness_status(witnesses.get('hermetic_matrix_sig', 'ABSTAIN:missing'))} | `{witnesses.get('hermetic_matrix_sig', 'N/A')[:32]}...` |
| Perf Gate | {format_witness_status(witnesses.get('perf_gate_sig', 'ABSTAIN:missing'))} | `{witnesses.get('perf_gate_sig', 'N/A')[:32]}...` |


```
[{status}] Epoch Seal <{epoch_hash}>
[{status}] Witnessed Epoch <{witnessed_epoch_hash}>
```


- Required PASS: {fleet_state['lane_summary']['required_pass']}
- Required ABSTAIN: {fleet_state['lane_summary']['required_abstain']}
- Optional PASS: {fleet_state['lane_summary']['optional_pass']}
- Optional ABSTAIN: {fleet_state['lane_summary']['optional_abstain']}

---

*Generated by AllBlue Epoch Seal Generator (RFC 8785)*  
*Timestamp: {fleet_state['timestamp']}*
"""
    
    return comment


def post_pr_comment(pr_number: int, comment: str, repo: Optional[str] = None) -> bool:
    """Post comment to PR using gh CLI."""
    
    cmd = ['gh', 'pr', 'comment', str(pr_number), '--body', comment]
    
    if repo:
        cmd.extend(['--repo', repo])
    
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True)
        return True
    except subprocess.CalledProcessError as e:
        print(f"ERROR: Failed to post PR comment: {e.stderr}", file=sys.stderr)
        return False


def main():
    """Main entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description='Post AllBlue Epoch Seal PR comment'
    )
    parser.add_argument(
        '--fleet-state',
        type=str,
        default='artifacts/allblue/fleet_state.json',
        help='Path to fleet state JSON file'
    )
    parser.add_argument(
        '--pr-number',
        type=int,
        help='PR number (auto-detected if not provided)'
    )
    parser.add_argument(
        '--repo',
        type=str,
        help='Repository in owner/repo format (auto-detected if not provided)'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Print comment without posting'
    )
    
    args = parser.parse_args()
    
    if not os.path.exists(args.fleet_state):
        print(f"ERROR: Fleet state not found: {args.fleet_state}", file=sys.stderr)
        sys.exit(1)
    
    fleet_state = load_fleet_state(args.fleet_state)
    
    comment = generate_pr_comment(fleet_state)
    
    if args.dry_run:
        print("=" * 70)
        print("PR Comment (Dry Run)")
        print("=" * 70)
        print(comment)
        sys.exit(0)
    
    pr_number = args.pr_number or get_pr_number()
    
    if not pr_number:
        print("ERROR: Could not determine PR number", file=sys.stderr)
        print("Provide --pr-number or run in GitHub Actions / PR context", file=sys.stderr)
        sys.exit(1)
    
    print(f"Posting epoch seal comment to PR #{pr_number}...")
    
    if post_pr_comment(pr_number, comment, args.repo):
        print(f"✓ Comment posted successfully")
        sys.exit(0)
    else:
        print(f"✗ Failed to post comment", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
