from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple


DOCS_DIR = Path(__file__).resolve().parent.parent / "docs" / "system_law"
INDEX_PATH = DOCS_DIR / "index.md"

# Lint/CI contract (spec only for now):
# - Default behavior rewrites index.md (equivalent to future `--write`).
# - A future `--check` flag should regenerate the content in memory and exit
#   with code 1 if index.md is not up to date, producing no file changes. CI
#   would run: `python tools/generate_system_law_index.py --check`.
# - `--write` (or no flag) would refresh index.md locally for contributors.

# Hand-authored descriptions keep the index readable. New files fall back to a
# generic description derived from the filename.
FILE_DESCRIPTIONS: Dict[str, str] = {
    "README.md": "Orientation for the system law materials.",
    "USLA_v0.1.md": "Universal system law agreement draft v0.1.",
    "canonical_update_operator.md": "Canonical update operator definition for system law changes.",
    "intervention_surface_map.md": "Map of intervention surfaces and control points.",
    "Phase_X_Divergence_Metric.md": "Metric specification for tracking Phase X divergence.",
    "Phase_X_Integration_Spec_v1.0.md": "Integration specification for Phase X v1.0.",
    "Phase_X_P2_Spec.md": "Phase X part 2 specification and rollout notes.",
    "Phase_X_P3_Spec.md": "Detailed specification for Phase X phase 3.",
    "Phase_X_P3P4_TODO.md": "To-do tracker for Phase X phases 3 and 4 readiness.",
    "Phase_X_P4_Spec.md": "Detailed specification for Phase X phase 4.",
    "Phase_X_Prelaunch_Review.md": "Pre-launch review package for Phase X.",
    "Replay_Safety_Governance_Law.md": "Replay safety governance policies and safeguards.",
    "SliceIdentity_PhaseX_Invariants.md": "Slice identity invariants defined for Phase X.",
}


def describe_file(filename: str) -> str:
    if filename in FILE_DESCRIPTIONS:
        return FILE_DESCRIPTIONS[filename]
    stem = Path(filename).stem.replace("_", " ").replace("-", " ")
    return f"Documentation for {stem}."


def collect_entries() -> List[Tuple[str, str]]:
    files = [
        path
        for path in DOCS_DIR.glob("*.md")
        if path.name.lower() != "index.md"
    ]
    files.sort(key=lambda p: p.name.lower())
    return [(path.name, describe_file(path.name)) for path in files]


def render_index(entries: List[Tuple[str, str]]) -> str:
    lines = [
        "<!-- Auto-generated by tools/generate_system_law_index.py; do not edit by hand. -->",
        "# System Law Documentation Index",
        "",
        "Run `python tools/generate_system_law_index.py` to refresh.",
        "",
    ]
    for filename, description in entries:
        lines.append(f"- `{filename}`: {description}")
    lines.extend(
        [
            "",
            "## Regeneration Instructions",
            "",
            "Run `python tools/generate_system_law_index.py` after adding/changing system law docs.",
            "",
        ]
    )
    lines.append("")
    return "\n".join(lines)


def write_index(contents: str) -> None:
    INDEX_PATH.write_text(contents, encoding="utf-8")


def parse_args(argv: Optional[List[str]]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate docs/system_law/index.md or check freshness."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate index.md is up to date without writing changes.",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Rewrite index.md (default behavior).",
    )
    args = parser.parse_args(argv)
    if args.check and args.write:
        parser.error("Use only one of --check or --write.")
    return args


def main(argv: Optional[List[str]] = None) -> int:
    args = parse_args(argv)
    entries = collect_entries()
    index_contents = render_index(entries)
    if args.check:
        if not INDEX_PATH.exists():
            print(
                "docs/system_law/index.md is missing. "
                "Run `python tools/generate_system_law_index.py`."
            )
            return 1
        current_contents = INDEX_PATH.read_text(encoding="utf-8")
        if current_contents == index_contents:
            print("docs/system_law/index.md is up to date.")
            return 0
        print(
            "docs/system_law/index.md is out of date. "
            "Run `python tools/generate_system_law_index.py` to refresh."
        )
        return 1

    write_index(index_contents)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
